### ISSUE TITLE
multiple threading

### ISSUE THREAD

**Issue by chuan137** [pgiri/asyncoro#3]
Hi pgiri,

I like this project, and its documentations. I actually learn a lot from it. 

My background is data scientist. As a newbie for asynchronous programming, my goals might be rather ambitious. I want to write a scheduler to control several machine in a small cluster, assigning processing tasks to them.

I know there is Hadoop, spark, and many map-reduce framework alike. But I still want to give a try by myself. because

1) our image processing jobs are computing intensive, I want to be flexible with computing, be it GPU computing, or many core computing or anything. I would like the scheduler can assign proper computing resources to each job, and being able to tune for performances.

2) I want to be flexible with data storage, our data is managed with other software, I want to be compatible, without importing them info HDFS or any specific system constrained by the framework. I would write a simple data module to extract them.

All being said, I feel asyncoro and dispy are conveniet tools for my purpose. And here is my question, which among a lot others, pops in my head on top. The Asyncoro scheduler seems to be single threaded. How about the coroutines? Are they wrapped into a single python thread or they are truly multiple threaded on hardware level? If I managed to build such a system, are they going to perform well in real work?

Thanks for you patient,
Chuan

**Comment by pgiri** [comment]
asyncoro and dispy are similar in some respects, but also differ quite a bit. If your tasks are compute intensive only, then using dispy is easier. See examples in dispy for various use cases. If you want to write your own scheduler to control which jobs are submitted where, that is also possible (see 'job_scheduler.py' example).

With dispy the jobs and client can't communicate; jobs can either send final results ("return" value) or provisional results (with "dispy_provisional_result" function). The client has no way to send information after a job is started. With asyncoro, client and computations can exchange information. asyncoro also supports distributed computing for compute intensive tasks, with discoro module and discoronode program. See 'discomp*' and 'discoro*' examples (README file in examples describes briefly what each example does). asyncoro itself uses one thread, but discoronode starts one asyncoro per processor so that all CPUs can be used for executing independent jobs.

If you are not sure you need asynchronous / message passing, you can start with dispy (since it is easier), and then migrate to asyncoro (if necessary). Either framework can use multi-core/multi-cpu nodes using processes, not threads (as threads in Python don't run more than one thread due to Global Interpreter Lock).

**Comment by pgiri** [comment]
You may find interesting / helpful to read http://blog.cloudimage.io/2015/02/18/rethinking-the-infrastructure/ which describes how they use dispy for image processing.

**Comment by pgiri** [comment]
This issue is not really an issue, I believe, so closing it. If there is a pending problem, please reopen.
